# Name: Fionn Hourican
# Student Number: 21477216
# I, Fionn Hourican, acknowledge all of DCU's Academic Integrity Policies.

myshell: myshell.c utility.c
	gcc -Wall myshell.c utility.c -o ../bin/myshell
